name: .NET CI

on: 
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Cache NuGet Packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --collect:"XPlat Code Coverage"

    # Assuming tests generate a `TestResults.xml` file
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: '**/TestResults/*.xml'
        reporter: dotnet-trx

    - name: Generate Coverage Report
      run: dotnet test --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput='./TestResults/Coverage/'

    - name: Upload Coverage Report to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: '**/TestResults/Coverage/*.xml'
        fail_ci_if_error: true
        
    - name: Install .NET Format (Lint)
      run: dotnet tool install -g dotnet-format

    - name: Lint with dotnet-format
      run: dotnet format --check

    - name: Perform Security Analysis with dotnet
      run: dotnet build /p:Configuration=Release /p:RunAnalyzersDuringBuild=true
      
    - uses: jwalton/gh-find-current-pr@v1
      id: find_pr
      
    - name: Add Code Coverage Comment to PR
      if: steps.find_pr.outputs.number
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        header: Code Coverage Report
        message: |
          ## Code Coverage Report
          ![Coverage Badge](./coverage-badge.svg)
          [Full report](./coverage-report.html)